name: PHP

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      matrix:
        php-versions: [ '8.0', '8.1' ]
    name: Tests - PHP ${{ matrix.php-versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extension: xdebug
          coverage: xdebug
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-suggest
      - name: Lint composer.json
        run: composer validate
      - name: Run Tests
        run: composer test
